language: python
dist: xenial
python: 3.7

branches:
  only:
    - master

services:
  - docker

env:
  global:
    - PIP_DISABLE_PIP_VERSION_CHECK=on
    - PIP_QUIET=1
    - DJANGO_VERSION=">=1.8,<1.9"

before_install:
  - docker build .
  - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
  - docker ps -a
  - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

install:
  - pip install -r requirements.txt

script: python manage.py test

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $S3_REGION
  app: 'example-app-name'
  env: 'example-app-environment'
  bucket_name: 'the-target-S3-bucket'
