language: python
dist: xenial
python: 3.7

branches:
  only:
    - master

services:
  - docker

env:
  global:
    - DJANGO_DEBUG=FALSE

# before_install:
#   - docker-compose up -d
#   - sleep 10

before_install:
  - docker build -t infodump-api .
  - docker run -d -p 127.0.0.1:8000:8000 --name app infodump-api sleep 60
  # - docker ps -a

# script:
#   - docker exec app python manage.py test

after_script:
  - docker rm -f app
  # - pip install --user awscli

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $EB_REGION
  app: $EB_APP_NAME
  env: $EB_ENV_NAME
  bucket_name: $S3_BUCKET_NAME
