language: python
dist: xenial
python: 3.7

branches:
  only:
    - master

services:
  - docker

env:
  global:
    - DJANGO_DEBUG=FALSE

before_install:
  - docker-compose up -d
  - sleep 10

install:
  - docker ps -a

script: python manage.py test

after_install:
  - docker-compose down

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $S3_REGION
  app: $EB_APP_NAME
  env: $EB_ENV_NAME
  bucket_name: $S3_BUCKET_NAME
